[package]
authors = ["Tim Toebrock"]
description = """
Create workouts in the MRC format.
"""
edition = "2021"
license = "MIT"
name = "mrc-workout-creator"
version = "0.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "6.0"
iced = {version = "0.13", features = ["async-std", "debug", "canvas"]}
iced_core = "0.13"
iced_runtime = "0.13.2"
regex = "1.11"
rfd = "0.15"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "1.13"
directories-next = "2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-timer = "0.2"
web-sys = {version = "0.3", features = ["Window", "Storage"]}
